update lfrc

diff --git a/.config/lf/lfrc b/.config/lf/lfrc
--- a/.config/lf/lfrc
+++ b/.config/lf/lfrc
@@ -38,12 +38,25 @@ cmd extract &{{
 }}
 
 # compress current file or selected files with tar and gunzip
-cmd tar &{{
+cmd tar ${{
     set -f
-    mkdir $1
-    cp -r $fx $1
-    tar czf $1.tar.gz $1
-    rm -rf $1
+    echo -n "Archive name: "
+    read name
+    mkdir "$name"
+
+    echo -n "Compression type (1-gzip, 2-xz, 3-bzip2): "
+    read type
+
+    cp -r $fx "$name"
+
+    case $type in
+        1) tar czf "$name.tar.gz" "$name" ;;
+        2) tar cJf "$name.tar.xz" "$name" ;;
+        3) tar cjf "$name.tar.bz2" "$name" ;;
+        *) echo "Invalid option"; rm -rf "$name"; exit 1 ;;
+    esac
+
+    rm -rf "$name"
 }}
 
 # compress current file or selected files with zip
@@ -77,6 +90,7 @@ map n
 map R bulk-rename
 map e $open_file $f
 map E extract
+map A tar
 map <enter> shell
 map an push %touch<space>
 map aa push %mkdir<space>
